### ISSUE TITLE
xFormers not available

### ISSUE THREAD

**Issue by micropsyche** [MackinationsAi/Upgraded-Depth-Anything-V2#10]
trying to run your modified code (thank you for your efforts), am getting,
xFormers not available
xFormers not available       (twice)

there is an xformers (no capital F) in venv\Lib\site-packages, is this the one the code is looking for?
apologies for the possibly trivial questions, but I am not a coder (of any flavour), however I have tried to look through the code and can't find where the call to xFormers is made.   Code still working on Windows (11). Thanks for your help.

**Comment by micropsyche** [comment]
Sorry, for the typo in the issues, code still not working under Windows (11).

**Comment by MackinationsAi** [comment]
I can't help unless you show me the error message/tracebacks that you are getting in cmd. Also, what gpu do you have bc anything less than 8-12gbs of VRAM you won't be able to run the vitb or vitl models (nothing I can do about that unfortunately, though you could rent cloud compute gpus from a service like runpod, run.ai, aws or any of the other cloud compute services out their).

**Comment by micropsyche** [comment]
Can't replicate the xformers problem, but Cmd tracebacks for current run are included. I am only a hobbyist and it looks like without a GPU, it may be better to just engage with an on-line provider for my depth maps, but local processing would be nice. Thank you for your kind assistance.

Please enter the path to the image file or directory containing images: "C:\Users\kensi\Pictures\Test Items for Gimp\barking owl GreyScale 20240613.JPG"
Processing images:   0%|                                                                                                                               | 0/1 [00:00<?, ?image/s]Progress 1/1: C:\Users\kensi\Pictures\Test Items for Gimp\barking owl GreyScale 20240613.JPG
Processing images:   0%|                                                                                                                               | 0/1 [00:00<?, ?image/s]
Traceback (most recent call last):
  File "c:\Users\kensi\Upgraded-Depth-Anything-V2\Upgraded-Depth-Anything-V2\run_image-depth_8bit.py", line 110, in <module>
    main()
  File "c:\Users\kensi\Upgraded-Depth-Anything-V2\Upgraded-Depth-Anything-V2\run_image-depth_8bit.py", line 103, in main
    process_image(args.img_path, args.outdir, args.input_size, args.encoder, args.pred_only, args.grayscale)
  File "c:\Users\kensi\Upgraded-Depth-Anything-V2\Upgraded-Depth-Anything-V2\run_image-depth_8bit.py", line 58, in process_image
    depth = depth_anything.infer_image(raw_image, input_size)
  File "C:\Users\kensi\Upgraded-Depth-Anything-V2\Upgraded-Depth-Anything-V2\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "c:\Users\kensi\Upgraded-Depth-Anything-V2\Upgraded-Depth-Anything-V2\depth_anything_v2\dpt.py", line 190, in infer_image
    depth = self.forward(image)
  File "c:\Users\kensi\Upgraded-Depth-Anything-V2\Upgraded-Depth-Anything-V2\depth_anything_v2\dpt.py", line 179, in forward
    features = self.pretrained.get_intermediate_layers(x, self.intermediate_layer_idx[self.encoder], return_class_token=True)
  File "c:\Users\kensi\Upgraded-Depth-Anything-V2\Upgraded-Depth-Anything-V2\depth_anything_v2\dinov2.py", line 308, in get_intermediate_layers
    outputs = self._get_intermediate_layers_not_chunked(x, n)
  File "c:\Users\kensi\Upgraded-Depth-Anything-V2\Upgraded-Depth-Anything-V2\depth_anything_v2\dinov2.py", line 277, in _get_intermediate_layers_not_chunked
    x = blk(x)
  File "C:\Users\kensi\Upgraded-Depth-Anything-V2\Upgraded-Depth-Anything-V2\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\kensi\Upgraded-Depth-Anything-V2\Upgraded-Depth-Anything-V2\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "c:\Users\kensi\Upgraded-Depth-Anything-V2\Upgraded-Depth-Anything-V2\depth_anything_v2\dinov2_layers\block.py", line 247, in forward
    return super().forward(x_or_x_list)
  File "c:\Users\kensi\Upgraded-Depth-Anything-V2\Upgraded-Depth-Anything-V2\depth_anything_v2\dinov2_layers\block.py", line 105, in forward
    x = x + attn_residual_func(x)
  File "c:\Users\kensi\Upgraded-Depth-Anything-V2\Upgraded-Depth-Anything-V2\depth_anything_v2\dinov2_layers\block.py", line 84, in attn_residual_func
    return self.ls1(self.attn(self.norm1(x)))
  File "C:\Users\kensi\Upgraded-Depth-Anything-V2\Upgraded-Depth-Anything-V2\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\kensi\Upgraded-Depth-Anything-V2\Upgraded-Depth-Anything-V2\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "c:\Users\kensi\Upgraded-Depth-Anything-V2\Upgraded-Depth-Anything-V2\depth_anything_v2\dinov2_layers\attention.py", line 76, in forward
    x = memory_efficient_attention(q, k, v, attn_bias=attn_bias)
  File "C:\Users\kensi\Upgraded-Depth-Anything-V2\Upgraded-Depth-Anything-V2\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 268, in memory_efficient_attention      
    return _memory_efficient_attention(
  File "C:\Users\kensi\Upgraded-Depth-Anything-V2\Upgraded-Depth-Anything-V2\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 387, in _memory_efficient_attention     
    return _memory_efficient_attention_forward(
  File "C:\Users\kensi\Upgraded-Depth-Anything-V2\Upgraded-Depth-Anything-V2\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 403, in _memory_efficient_attention_forward
    op = _dispatch_fw(inp, False)
  File "C:\Users\kensi\Upgraded-Depth-Anything-V2\Upgraded-Depth-Anything-V2\venv\lib\site-packages\xformers\ops\fmha\dispatch.py", line 125, in _dispatch_fw
    return _run_priority_list(
  File "C:\Users\kensi\Upgraded-Depth-Anything-V2\Upgraded-Depth-Anything-V2\venv\lib\site-packages\xformers\ops\fmha\dispatch.py", line 65, in _run_priority_list
    raise NotImplementedError(msg)
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(1, 2073, 16, 64) (torch.float32)
     key         : shape=(1, 2073, 16, 64) (torch.float32)
     value       : shape=(1, 2073, 16, 64) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`decoderF` is not supported because:
    device=cpu (supported: {'cuda'})
    attn_bias type is <class 'NoneType'>
`flshattF@v2.5.6` is not supported because:
    device=cpu (supported: {'cuda'})
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
`cutlassF` is not supported because:
    device=cpu (supported: {'cuda'})
`smallkF` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 32
    device=cpu (supported: {'cuda'})
    unsupported embed per head: 64

(venv) c:\Users\kensi\Upgraded-Depth-Anything-V2\Upgraded-Depth-Anything-V2>
 *  History restored 

Microsoft Windows [Version 10.0.22631.3880]
(c) Microsoft Corporation. All rights reserved.

**Comment by heyoeyo** [comment]
This looks like the same problem as #6, which is that xformers doesn't work with cpu (and the image encoder isn't built in a way to fallback nicely when a gpu isn't available). If you're just using depth-anything itself, uninstalling xformers should fix things, otherwise you can modify the code as mentioned in that other issue.

Depth-anything should run fine on cpu (especially the small model), though a gpu will help if you're running on video or going to be processing 1000's of images!
